# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 132f1f3455a0c3480ccca62799e87ee803469b51e89ca674f5a6f6b053659dba9a047b1ab30475b94e1baf7100a480197c17c4463f1caf962273db703d4e6150

test:
  secret_key_base: ddb38ac8609e817efd14005a33f46425f9a0c0482eec92f7139620acdc80d3dfa3addd01b5d1bae855c475247908eb73dd82440bac08c42583841848ee55a150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
